package io.bluetrace.opentrace.bluetooth.gatt

import io.bluetrace.opentrace.BuildConfig

const val ACTION_RECEIVED_STREETPASS =
    "${BuildConfig.APPLICATION_ID}.ACTION_RECEIVED_STREETPASS"
const val ACTION_RECEIVED_STATUS =
    "${BuildConfig.APPLICATION_ID}.ACTION_RECEIVED_STATUS"
const val DEVICE_DATA = "${BuildConfig.APPLICATION_ID}.DEVICE_DATA"
const val DEVICE_ADDRESS = "${BuildConfig.APPLICATION_ID}.DEVICE_ADDRESS"
const val SIGNAL_STRENGTH = "${BuildConfig.APPLICATION_ID}.SIGNAL_STRENGTH"
const val TRANSMISSION_POWER = "${BuildConfig.APPLICATION_ID}.TRANSMISSION_POWER"
const val CONNECTION_DATA = "${BuildConfig.APPLICATION_ID}.CONNECTION_DATA"

const val STREET_PASS = "${BuildConfig.APPLICATION_ID}.STREET_PASS"
const val STATUS = "${BuildConfig.APPLICATION_ID}.STATUS"

const val ACTION_DEVICE_PROCESSED = "${BuildConfig.APPLICATION_ID}.ACTION_DEVICE_PROCESSED"
const val ACTION_GATT_DISCONNECTED = "${BuildConfig.APPLICATION_ID}.ACTION_GATT_DISCONNECTED"

